name: tests
on:
  push:
  pull_request:

jobs:
  tests_on_ubuntu_x86_64:
    name: Tests on Ubuntu (x86_64 and i686)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install packages
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y gcc-multilib libgcc-s1:i386 libstdc++6:i386
        sudo apt-get remove mono-runtime
    - name: build
      run: |
        cd tests && make cross
    - name: x86_64 -> x86_64
      run: |
        cd tests && ./test-prog-x86_64 x86_64
    - name: x86_64 -> i386
      run: |
        cd tests && ./test-prog-x86_64 i386
    - name: i386 -> i386
      run: |
        cd tests && ./test-prog-i386 i386
    - name: x86_64 -> x86_64 (cloned thread)
      run: |
        cd tests && ./test-prog-x86_64 x86_64 --cloned-thread

  tests_on_alpine_x86_64:
    name: Tests on Alpine (x86_64 only)
    runs-on: ubuntu-latest
    container: alpine
    steps:
    - name: Install packages
      run: |
        apk add gcc musl-dev git make
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: run tests
      run: |
        make check
